-- Index contract mirrored from AMS99 reference schema.
CREATE INDEX idx_dpp_account ON delivery_person_payment (payment_account_id);
CREATE INDEX idx_dpp_alloc ON delivery_person_payment (allocation_id);
CREATE INDEX idx_dpp_date ON delivery_person_payment (date_posted);
CREATE INDEX idx_dpp_person ON delivery_person_payment (delivery_person_id);
CREATE INDEX ix_account_category_created_at ON account_category (created_at);
CREATE INDEX ix_account_category_name ON account_category (name);
CREATE INDEX ix_account_created_at ON account (created_at);
CREATE INDEX ix_account_is_active ON account (is_active);
CREATE INDEX ix_account_opening_balance_date ON account (opening_balance_date);
CREATE INDEX ix_account_reconciliation_account_id ON account_reconciliation (account_id);
CREATE INDEX ix_account_reconciliation_adjustment_transaction_id ON account_reconciliation (adjustment_transaction_id);
CREATE INDEX ix_account_reconciliation_created_at ON account_reconciliation (created_at);
CREATE INDEX ix_account_reconciliation_difference_type ON account_reconciliation (difference_type);
CREATE INDEX ix_account_reconciliation_previous_reconciliation_id ON account_reconciliation (previous_reconciliation_id);
CREATE INDEX ix_account_reconciliation_reconciliation_date ON account_reconciliation (reconciliation_date);
CREATE INDEX ix_account_reconciliation_status ON account_reconciliation (status);
CREATE INDEX ix_account_reconciliation_updated_at ON account_reconciliation (updated_at);
CREATE INDEX ix_account_source_category ON account (source_category);
CREATE INDEX ix_account_transaction_created_at ON account_transaction (created_at);
CREATE INDEX ix_account_transaction_date_posted ON account_transaction (date_posted);
CREATE INDEX ix_account_transaction_from_account_id ON account_transaction (from_account_id);
CREATE INDEX ix_account_transaction_is_void ON account_transaction (is_void);
CREATE INDEX ix_account_transaction_reconciliation_id ON account_transaction (reconciliation_id);
CREATE INDEX ix_account_transaction_source_id ON account_transaction (source_id);
CREATE INDEX ix_account_transaction_source_type ON account_transaction (source_type);
CREATE INDEX ix_account_transaction_to_account_id ON account_transaction (to_account_id);
CREATE INDEX ix_account_transaction_transaction_type ON account_transaction (transaction_type);
CREATE INDEX ix_account_updated_at ON account (updated_at);
CREATE INDEX ix_accounting_audit_log_action ON accounting_audit_log (action);
CREATE INDEX ix_accounting_audit_log_created_at ON accounting_audit_log (created_at);
CREATE INDEX ix_accounting_audit_log_entity_id ON accounting_audit_log (entity_id);
CREATE INDEX ix_accounting_audit_log_entity_type ON accounting_audit_log (entity_type);
CREATE INDEX ix_accounting_audit_log_module ON accounting_audit_log (module);
CREATE INDEX ix_accounting_audit_log_user_id ON accounting_audit_log (user_id);
CREATE INDEX ix_accounting_audit_log_username ON accounting_audit_log (username);
CREATE INDEX ix_audit_log_timestamp ON audit_log (timestamp);
CREATE INDEX ix_audit_log_username ON audit_log (username);
CREATE INDEX ix_bill_counter_namespace ON bill_counter (namespace);
CREATE INDEX ix_booking_allocation_booking_item_id ON booking_allocation (booking_item_id);
CREATE INDEX ix_booking_allocation_repair_archive_archived_at ON booking_allocation_repair_archive (archived_at);
CREATE INDEX ix_booking_allocation_repair_archive_original_allocation_id ON booking_allocation_repair_archive (original_allocation_id);
CREATE INDEX ix_booking_allocation_repair_archive_repair_run_id ON booking_allocation_repair_archive (repair_run_id);
CREATE INDEX ix_booking_allocation_sale_id ON booking_allocation (sale_id);
CREATE INDEX ix_booking_allocation_sale_item_id ON booking_allocation (sale_item_id);
CREATE INDEX ix_booking_auto_bill_no    ON booking(auto_bill_no);
CREATE INDEX ix_booking_date_posted ON booking (date_posted);
CREATE INDEX ix_booking_manual_bill_no  ON booking(manual_bill_no);
CREATE INDEX ix_cash_flow_category_direction ON cash_flow_category (direction);
CREATE INDEX ix_cash_flow_category_is_active ON cash_flow_category (is_active);
CREATE INDEX ix_cash_flow_category_name ON cash_flow_category (name);
CREATE INDEX ix_cash_flow_difference_adjustment_adjustment_date ON cash_flow_difference_adjustment (adjustment_date);
CREATE INDEX ix_cash_flow_difference_adjustment_created_at ON cash_flow_difference_adjustment (created_at);
CREATE INDEX ix_cash_flow_difference_adjustment_updated_at ON cash_flow_difference_adjustment (updated_at);
CREATE INDEX ix_cash_flow_entry_account_id ON cash_flow_entry (account_id);
CREATE INDEX ix_cash_flow_entry_audit_action ON cash_flow_entry_audit (action);
CREATE INDEX ix_cash_flow_entry_audit_changed_at ON cash_flow_entry_audit (changed_at);
CREATE INDEX ix_cash_flow_entry_audit_entry_id ON cash_flow_entry_audit (entry_id);
CREATE INDEX ix_cash_flow_entry_category_id ON cash_flow_entry (category_id);
CREATE INDEX ix_cash_flow_entry_date_posted ON cash_flow_entry (date_posted);
CREATE INDEX ix_cash_flow_entry_direction ON cash_flow_entry (direction);
CREATE INDEX ix_cash_flow_entry_is_void ON cash_flow_entry (is_void);
CREATE INDEX ix_cash_flow_entry_party_id ON cash_flow_entry (party_id);
CREATE INDEX ix_cash_flow_entry_party_name ON cash_flow_entry (party_name);
CREATE INDEX ix_cash_flow_entry_party_type ON cash_flow_entry (party_type);
CREATE INDEX ix_cash_flow_entry_subcategory_id ON cash_flow_entry (subcategory_id);
CREATE INDEX ix_cash_flow_party_is_active ON cash_flow_party (is_active);
CREATE INDEX ix_cash_flow_party_name ON cash_flow_party (name);
CREATE INDEX ix_cash_flow_party_party_type ON cash_flow_party (party_type);
CREATE INDEX ix_cash_flow_reconciliation_audit_adjustment_date ON cash_flow_reconciliation_audit (adjustment_date);
CREATE INDEX ix_cash_flow_reconciliation_audit_changed_at ON cash_flow_reconciliation_audit (changed_at);
CREATE INDEX ix_cash_flow_reconciliation_audit_reconciliation_id ON cash_flow_reconciliation_audit (reconciliation_id);
CREATE INDEX ix_cash_flow_subcategory_category_id ON cash_flow_subcategory (category_id);
CREATE INDEX ix_cash_flow_subcategory_is_active ON cash_flow_subcategory (is_active);
CREATE INDEX ix_cash_flow_subcategory_name ON cash_flow_subcategory (name);
CREATE INDEX ix_client_created_at ON client (created_at);
CREATE INDEX ix_client_opening_balance_date ON client (opening_balance_date);
CREATE INDEX ix_delivery_date_posted ON delivery (date_posted);
CREATE INDEX ix_delivery_person_created_at ON delivery_person (created_at);
CREATE INDEX ix_delivery_person_opening_balance_date ON delivery_person (opening_balance_date);
CREATE INDEX ix_delivery_person_payment_allocation_id ON delivery_person_payment (allocation_id);
CREATE INDEX ix_delivery_person_payment_created_at ON delivery_person_payment (created_at);
CREATE INDEX ix_delivery_person_payment_date_posted ON delivery_person_payment (date_posted);
CREATE INDEX ix_delivery_person_payment_delivery_person_id ON delivery_person_payment (delivery_person_id);
CREATE UNIQUE INDEX ix_delivery_person_payment_idempotency_key ON delivery_person_payment (idempotency_key);
CREATE INDEX ix_delivery_person_payment_is_void ON delivery_person_payment (is_void);
CREATE INDEX ix_delivery_person_payment_payment_account_id ON delivery_person_payment (payment_account_id);
CREATE INDEX ix_delivery_person_payment_reference ON delivery_person_payment (reference);
CREATE INDEX ix_delivery_person_payment_sale_id ON delivery_person_payment (sale_id);
CREATE INDEX ix_delivery_person_payment_updated_at ON delivery_person_payment (updated_at);
CREATE INDEX ix_delivery_rent_bill_no ON delivery_rent (bill_no);
CREATE INDEX ix_delivery_rent_date_posted ON delivery_rent (date_posted);
CREATE INDEX ix_delivery_rent_delivery_person_name ON delivery_rent (delivery_person_name);
CREATE INDEX ix_delivery_rent_is_void ON delivery_rent (is_void);
CREATE INDEX ix_delivery_rent_sale_id ON delivery_rent (sale_id);
CREATE INDEX ix_direct_sale_auto_bill_no   ON direct_sale(auto_bill_no);
CREATE INDEX ix_direct_sale_client_code ON direct_sale (client_code);
CREATE INDEX ix_direct_sale_date_posted ON direct_sale (date_posted);
CREATE INDEX ix_direct_sale_draft_created_at ON direct_sale_draft (created_at);
CREATE INDEX ix_direct_sale_draft_updated_at ON direct_sale_draft (updated_at);
CREATE INDEX ix_direct_sale_idempotency_key ON direct_sale (idempotency_key);
CREATE INDEX ix_direct_sale_manual_bill_no ON direct_sale(manual_bill_no);
CREATE INDEX ix_entry_bill_no           ON entry(bill_no);
CREATE INDEX ix_entry_created_at ON entry (created_at);
CREATE INDEX ix_entry_material          ON entry(material);
CREATE INDEX ix_entry_source_bill_no ON entry (source_bill_no);
CREATE INDEX ix_entry_source_id ON entry (source_id);
CREATE INDEX ix_entry_source_module ON entry (source_module);
CREATE INDEX ix_entry_source_table ON entry (source_table);
CREATE INDEX ix_entry_transaction_type ON entry (transaction_type);
CREATE INDEX ix_entry_type              ON entry(type);
CREATE INDEX ix_fbm_cash_drawer_category_created_at ON fbm_cash_drawer_category (created_at);
CREATE INDEX ix_fbm_cash_drawer_category_is_active ON fbm_cash_drawer_category (is_active);
CREATE INDEX ix_fbm_cash_drawer_category_name ON fbm_cash_drawer_category (name);
CREATE INDEX ix_fbm_cash_drawer_entry_date_posted ON fbm_cash_drawer_entry (date_posted);
CREATE INDEX ix_fbm_cash_drawer_entry_entry_type ON fbm_cash_drawer_entry (entry_type);
CREATE INDEX ix_fbm_cash_drawer_entry_is_void ON fbm_cash_drawer_entry (is_void);
CREATE INDEX ix_fbm_cash_drawer_entry_method ON fbm_cash_drawer_entry (method);
CREATE INDEX ix_fbm_cash_drawer_entry_source ON fbm_cash_drawer_entry (source);
CREATE INDEX ix_fbm_client_created_at ON fbm_client (created_at);
CREATE INDEX ix_fbm_rental_created_at ON fbm_rental (created_at);
CREATE INDEX ix_fbm_rental_item_created_at ON fbm_rental_item (created_at);
CREATE INDEX ix_fbm_rental_return_datetime ON fbm_rental (return_datetime);
CREATE INDEX ix_fbm_rental_start_datetime ON fbm_rental (start_datetime);
CREATE INDEX ix_follow_up_contact_created_at ON follow_up_contact (created_at);
CREATE INDEX ix_follow_up_reminder_created_at ON follow_up_reminder (created_at);
CREATE INDEX ix_future_account_audit_log_created_at ON future_account_audit_log (created_at);
CREATE INDEX ix_grn_allocation_grn_item_id ON grn_allocation (grn_item_id);
CREATE INDEX ix_grn_allocation_is_void ON grn_allocation (is_void);
CREATE INDEX ix_grn_allocation_sale_id ON grn_allocation (sale_id);
CREATE INDEX ix_grn_allocation_sale_item_id ON grn_allocation (sale_item_id);
CREATE INDEX ix_grn_auto_bill_no        ON grn(auto_bill_no);
CREATE INDEX ix_grn_date_posted ON grn (date_posted);
CREATE INDEX ix_grn_item_is_locked ON grn_item (is_locked);
CREATE INDEX ix_grn_item_is_void ON grn_item (is_void);
CREATE INDEX ix_grn_manual_bill_no      ON grn(manual_bill_no);
CREATE INDEX ix_import_history_entry_import_job_id ON import_history_entry (import_job_id);
CREATE INDEX ix_import_history_entry_recorded_at ON import_history_entry (recorded_at);
CREATE INDEX ix_import_job_status ON import_job (status);
CREATE INDEX ix_import_upload_status ON import_upload (status);
CREATE UNIQUE INDEX ix_import_upload_upload_id ON import_upload (upload_id);
CREATE INDEX ix_material_category_created_at ON material_category (created_at);
CREATE INDEX ix_material_category_id ON material (category_id);
CREATE INDEX ix_material_created_at ON material (created_at);
CREATE INDEX ix_material_return_auto_bill_no    ON material_return(auto_bill_no);
CREATE INDEX ix_material_return_date_posted ON material_return (date_posted);
CREATE INDEX ix_material_return_is_void ON material_return (is_void);
CREATE INDEX ix_material_return_item_material_return_id ON material_return_item (material_return_id);
CREATE INDEX ix_material_return_manual_bill_no  ON material_return(manual_bill_no);
CREATE INDEX ix_material_return_payment_id ON material_return (payment_id);
CREATE INDEX ix_payment_auto_bill_no    ON payment(auto_bill_no);
CREATE INDEX ix_payment_client_id ON payment (client_id);
CREATE INDEX ix_payment_created_at ON payment (created_at);
CREATE INDEX ix_payment_date_posted ON payment (date_posted);
CREATE UNIQUE INDEX ix_payment_idempotency_key ON payment (idempotency_key);
CREATE INDEX ix_payment_is_void ON payment (is_void);
CREATE INDEX ix_payment_manual_bill_no  ON payment(manual_bill_no);
CREATE INDEX ix_payment_payment_type ON payment (payment_type);
CREATE INDEX ix_payment_source_id ON payment (source_id);
CREATE INDEX ix_payment_source_type ON payment (source_type);
CREATE INDEX ix_payment_updated_at ON payment (updated_at);
CREATE INDEX ix_pending_bill_bill_kind ON pending_bill (bill_kind);
CREATE INDEX ix_pending_bill_bill_no    ON pending_bill(bill_no);
CREATE INDEX ix_pending_bill_client_code ON pending_bill(client_code);
CREATE INDEX ix_pending_bill_source_bill_no ON pending_bill (source_bill_no);
CREATE INDEX ix_pending_bill_source_id ON pending_bill (source_id);
CREATE INDEX ix_pending_bill_source_module ON pending_bill (source_module);
CREATE INDEX ix_pending_bill_source_table ON pending_bill (source_table);
CREATE INDEX ix_pending_bill_transaction_type ON pending_bill (transaction_type);
CREATE INDEX ix_recon_basket_created_at ON recon_basket (created_at);
CREATE INDEX ix_root_backup_email_history_created_at ON root_backup_email_history (created_at);
CREATE INDEX ix_root_backup_email_history_status ON root_backup_email_history (status);
CREATE INDEX ix_root_backup_email_history_trigger_type ON root_backup_email_history (trigger_type);
CREATE INDEX ix_root_backup_settings_updated_at ON root_backup_settings (updated_at);
CREATE INDEX ix_root_recovery_code_created_at ON root_recovery_code (created_at);
CREATE INDEX ix_root_recovery_code_used_at ON root_recovery_code (used_at);
CREATE INDEX ix_root_recovery_code_username ON root_recovery_code (username);
CREATE INDEX ix_sale_delivery_persons_created_at ON sale_delivery_persons (created_at);
CREATE INDEX ix_sale_delivery_persons_delivery_person_id ON sale_delivery_persons (delivery_person_id);
CREATE INDEX ix_sale_delivery_persons_is_void ON sale_delivery_persons (is_void);
CREATE INDEX ix_sale_delivery_persons_sale_id ON sale_delivery_persons (sale_id);
CREATE INDEX ix_staff_email_created_at ON staff_email (created_at);
CREATE INDEX ix_supplier_created_at ON supplier (created_at);
CREATE INDEX ix_supplier_opening_balance_date ON supplier (opening_balance_date);
CREATE INDEX ix_supplier_payment_auto_bill_no   ON supplier_payment(auto_bill_no);
CREATE INDEX ix_supplier_payment_created_at ON supplier_payment (created_at);
CREATE INDEX ix_supplier_payment_date_posted ON supplier_payment (date_posted);
CREATE UNIQUE INDEX ix_supplier_payment_idempotency_key ON supplier_payment (idempotency_key);
CREATE INDEX ix_supplier_payment_is_void ON supplier_payment (is_void);
CREATE INDEX ix_supplier_payment_manual_bill_no ON supplier_payment(manual_bill_no);
CREATE INDEX ix_supplier_payment_payment_type ON supplier_payment (payment_type);
CREATE INDEX ix_supplier_payment_source_id ON supplier_payment (source_id);
CREATE INDEX ix_supplier_payment_source_type ON supplier_payment (source_type);
CREATE INDEX ix_supplier_payment_supplier_id ON supplier_payment (supplier_id);
CREATE INDEX ix_supplier_payment_updated_at ON supplier_payment (updated_at);
CREATE INDEX ix_system_lock_acquired_at ON system_lock (acquired_at);
CREATE UNIQUE INDEX ix_system_lock_name ON system_lock (name);
CREATE INDEX ix_system_lock_status ON system_lock (status);
CREATE INDEX ix_tenant_wipe_backup_history_created_at ON tenant_wipe_backup_history (created_at);
CREATE INDEX ix_tenant_wipe_backup_history_wipe_status ON tenant_wipe_backup_history (wipe_status);
CREATE INDEX ix_user_login_session_created_at ON user_login_session (created_at);
CREATE INDEX ix_user_login_session_ended_at ON user_login_session (ended_at);
CREATE INDEX ix_user_login_session_ip ON user_login_session (ip);
CREATE INDEX ix_user_login_session_last_seen_at ON user_login_session (last_seen_at);
CREATE UNIQUE INDEX ix_user_login_session_sid ON user_login_session (sid);
CREATE INDEX ix_user_login_session_user_id ON user_login_session (user_id);
CREATE INDEX ix_user_login_session_username ON user_login_session (username);
CREATE INDEX ix_waive_off_bill_no ON waive_off (bill_no);
CREATE INDEX ix_waive_off_client_code ON waive_off (client_code);
CREATE INDEX ix_waive_off_client_name ON waive_off (client_name);
CREATE INDEX ix_waive_off_date_posted ON waive_off (date_posted);
CREATE INDEX ix_waive_off_is_void ON waive_off (is_void);
CREATE INDEX ix_waive_off_payment_id ON waive_off (payment_id);
CREATE UNIQUE INDEX uq_cash_flow_entry_idempotency_key ON cash_flow_entry(idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX uq_delivery_person_payment_idempotency_key ON delivery_person_payment(idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX uq_direct_sale_idempotency_key ON direct_sale(idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX uq_grn_manual_bill_no ON grn(manual_bill_no) WHERE manual_bill_no IS NOT NULL AND TRIM(manual_bill_no) <> '';
CREATE UNIQUE INDEX uq_payment_idempotency_key ON payment(idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX uq_supplier_payment_idempotency_key ON supplier_payment(idempotency_key) WHERE idempotency_key IS NOT NULL;
